chart/urls.py
from django.urls import path

from . import views

app_name = "chart"

urlpatterns = [
    path("", views.index, name="index"),
    path("tickers/", views.find_ticker, name="ticker"),
    path("keywords/", views.keywords, name="keywords"),
    path("keywords/edit", views.keywords_edit, name="keywords_edit"),
    path("keywords/edit_complete", views.keywords_edit_complete, name="keywords_edit_complete"),
    path("company/<str:ticker>/", views.inquiry, name="inquiry"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("chart.urls")),
    path("admin/", admin.site.urls),
]

handler404 = "chart.views.page_not_found"

chart/models.py
from django.db import models


class Company(models.Model):
    ticker = models.CharField(max_length=9, primary_key=True)
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.ticker


class Keyword(models.Model):
    id = models.AutoField(primary_key=True)
    keyword = models.CharField(max_length=40)
    ticker_id = models.ForeignKey(Company, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.ticker_id.ticker} - {self.keyword}"

chart/forms.py
from django import forms

from .models import Ticker


class TickerForm(forms.ModelForm):
    class Meta:
        model = Ticker
        fields = ["ticker", "keywords"]

chart/views.py
import json
import urllib

from django.http import HttpResponse
from django.shortcuts import render, redirect

from .graph import NoDataError, get_graph
from .models import Company


def index(request):
    return render(request, "chart/index.html")


def inquiry(request, ticker):
    DEFAULT_DURATION = "5Y"
    duration = request.GET.get("duration", DEFAULT_DURATION)

    topics = list(Company.objects.get(
        ticker=ticker).keyword_set.values_list('keyword', flat=True))

    try:
        graphs, names = get_graph(ticker, duration, topics)
    except RuntimeError:
        return HttpResponse("Google Trends returned 429 error. Please refresh the page (F5).")
    except NoDataError as e:
        return HttpResponse(f"{e}<br>Go <a href='/'>Home</a>")
    context = {"graphs": zip(graphs, names)}

    return render(request, "chart/chart.html", context)


def fetch_name_from_ticker(ticker):
    # get company name from ticker
    payload = f"https://query2.finance.yahoo.com/v1/finance/search?q={ticker}"
    response = urllib.request.urlopen(payload)
    content = response.read()
    data = json.loads(content.decode("utf8"))["quotes"][0]["shortname"]

    return data


def keywords(request):
    if request.method == "POST":
        ticker = request.POST.get("ticker")
        kws = request.POST.getlist("keywords")

        name = fetch_name_from_ticker(ticker)
        company, created = Company.objects.get_or_create(
            ticker=ticker, name=name)
        for keyword in kws:
            company.keyword_set.create(keyword=keyword)
        return redirect("chart:index")
    else:
        tickers = get_all_tickers()
        context = {"tickers": tickers}
        return render(request, "chart/keyword.html", context)


def keywords_edit(request):
    ticker = request.POST.get("ticker")
    kws = Company.objects.get(ticker=ticker) \
        .keyword_set.values_list("keyword", flat=True)
    context = {"ticker": ticker, "keywords": kws}
    return render(request, "chart/keywords_edit.html", context)


def keywords_edit_complete(request):
    ticker = request.POST.get("ticker")
    kws = request.POST.getlist("keywords")

    company = Company.objects.get(ticker=ticker)
    company.keyword_set.all().delete()
    for kw in kws:
        company.keyword_set.create(keyword=kw)
    return redirect("chart:index")


def find_ticker(request):
    if request.method == "GET":
        tickers = get_all_tickers()

        return HttpResponse(
            json.dumps({"tickers": list(tickers)}), content_type="application/json"
        )


def get_all_tickers():
    return Company.objects.values_list("ticker", flat=True)


def page_not_found(request, exception):
    return render(request, "chart/404.html", {})

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous" />
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous">
  </script>
  <link rel="stylesheet" href="{% static 'mystyle.css' %}" />
  <title>Main</title>
  <script src="https://kit.fontawesome.com/000c60520d.js" crossorigin="anonymous"></script>
</head>

<body>
  {% include 'navbar.html' %}
  {% block contents %}{% endblock %}
  {% block script %}{% endblock %}
</body>

</html>

templates/chart/chart.html
{% extends 'base.html' %}

{% block contents %}
<div class="container mt-3">
    <div class="row justify-content-center">
        {% for graph in graphs %}
        <div class="col-lg-4 mb-3">
            <div class="card">
                <div class="card-header">{{ graph.1 }}</div>
                <img src="data:image/png;base64,{{ graph.0 }}" class="card-img-top">
                <div class="card-body">
                    <div class="btn-group" role="group" aria-label="Basic example">
                        {% comment %} <button type="button" class="btn btn-outline-dark"><i
                                class="fa fa-file-arrow-down"></i></button> {% endcomment %}
                        <a type="button" class="btn btn-outline-dark btn-sm" href="?duration=5Y">5Y</a>
                        <a type="button" class="btn btn-outline-dark btn-sm" href="?duration=1.5Y">1.5Y</a>
                        <a type="button" class="btn btn-outline-dark btn-sm" href="?duration=9M">9M</a>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/chart/index.html
{% extends 'base.html' %}

{% block contents %}
{% load static %}
<div class="container">
    <div class="row justify-content-center my-5">
        <img src="{% static 'images/logo_home.jpeg' %}" id="search-logo" />
    </div>
    <div class="row d-flex justify-content-center">
        <div class="col-md-4">
            <div class="form-floating">
                <i class="fa fa-search"></i>
                <input type="text" id="search-input" class="form-control form-input" placeholder="Ticker"
                    maxlength="26">
                <label id="ticker_label" for="search-input">Ticker</label>
            </div>
        </div>
    </div>
    <div class="row d-flex justify-content-center">
        <div class="col-md-4 list-group" id="search-results" style="padding-left: 12px">
        </div>
    </div>
</div>
{% endblock %}

{% block script %}
<script>
    let search_box = document.getElementById("search-input");
    search_box.addEventListener("keyup", function (e) {
        let display_area = document.getElementById("search-results");
        display_area.innerHTML = "";

        // If the text is empty, skip to fetch information
        if (e.target.value === "") {
            return;
        }

        let search_text = e.target.value.toUpperCase();

        // TODO: 전체 리스트를 받아오는 거에서 검색하는 걸로 바꿔야 함
        fetch("{% url 'chart:ticker' %}")
            .then((response) => {
                if (!response.ok) {
                    throw new Error('400 아니면 500 에러남.');
                }
                return response.json();
            })
            .then((suggestions) => {
                let tickers = suggestions['tickers'];

                display_area.innerHTML = "";

                tickers.forEach(element => {
                    for (let i = 0; i < search_text.length; i++) {
                        if (element[i] !== search_text[i]) {
                            return;
                        }
                    }
                    // The 11111 works as a placeholder for the ticker
                    // Cannot identify how this works internally
                    let url = "{% url 'chart:inquiry' 11111 %}".replace('/11111/', '/' + element);
                    display_area.insertAdjacentHTML("beforeend",
                        `<a type="button" href="${url}" class="list-group-item list-group-item-action">
                            <i class="fa fa-search"></i>
                            <span style="margin-left: 8px;">${element}</span>
                        </a>`);
                });
            });
    });
</script>
{% endblock %}

templates/chart/keyword.html
{% extends 'base.html' %}

{% block contents %}
<div class="container mt-3">
    <div class="row">
        <div class="col">
            <form method="post" action="{% url 'chart:keywords_edit' %}" class="mb-3">
                {% csrf_token %}
                <label class="form-label">List of Tickers</label>
                <select class="form-select mb-3" name="ticker" required>
                    {% for ticker in tickers %}
                        <option value="{{ ticker }}">{{ ticker }}</option>
                    {% endfor %}
                </select>
                <button id="edit_keywords" type="submit" class="btn btn-primary">Edit Keywords</button>
            </form>
        </div>

        <div class="col">
            <form method="post">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="ticker" class="form-label">New Ticker</label>
                    <input type="text" class="form-control" id="ticker" name="ticker" maxlength="9" required>
                </div>
                <div class="mb-3">
                    <label class="form-label">Keywords</label>
                    <div class="input-group">
                        <input type="text" name="keywords" class="form-control" maxlength="40" required>
                        <button class="btn btn-outline-secondary add-key" type="button"><i
                                class="fa-solid fa-plus"></i></button>
                    </div>
                </div>
                <button id="save_button" type="submit" class="btn btn-primary">Save</button>
            </form>

        </div>
    </div>
</div>
</div>
{% endblock %}

{% block script %}
<script>
    function append_button() {
        const div = document.createElement("div");
        div.classList.add("input-group", "mb-3");

        const input = document.createElement("input");
        input.type = "text";
        input.classList.add("form-control");
        input.maxLength = 40;
        input.required = true;
        input.name = "keywords";

        const plus_button = document.createElement("button");
        plus_button.classList.add("btn", "btn-outline-secondary", "add-key");
        plus_button.type = "button";
        plus_button.innerHTML = '<i class="fa-solid fa-plus"></i>';
        plus_button.addEventListener("click", append_button);

        const minus_button = document.createElement("button");
        minus_button.classList.add("btn", "btn-outline-secondary", "sub-key");
        minus_button.type = "button";
        minus_button.innerHTML = '<i class="fa-solid fa-minus"></i>';
        minus_button.addEventListener("click", () => {
            minus_button.parentElement.remove();
        });

        div.appendChild(input);
        div.appendChild(plus_button);
        div.appendChild(minus_button);

        document.getElementById("save_button").before(div);
    }

    let add_keys = document.getElementsByClassName("add-key");
    Array.from(add_keys).forEach((add_key) => {
        add_key.addEventListener("click", append_button);
    });
</script>
{% endblock %}

templates/chart/keywords_edit.html
{% extends 'base.html' %}
{% block contents %}
<div class="container mt-3 col-4">
    <form method="post" action="{% url 'chart:keywords_edit_complete' %}">
        {% csrf_token %}
        <label class="form-label">{{ ticker }}</label>
        <input type="hidden" name="ticker" value="{{ ticker }}">
        <div class="mb-3">
            {% for keyword in keywords %}
            {% if forloop.counter0 != 0 %}
            <div class="input-group mb-3">
                <input type="text" name="keywords" class="form-control" value="{{ keyword }}" maxlength="40" required>
                <button class="btn btn-outline-secondary add-key" type="button"><i
                        class="fa-solid fa-plus"></i></button>
                <button class="btn btn-outline-secondary sub-key" type="button"><i
                        class="fa-solid fa-minus"></i></button>
            </div>
            {% else %}
            <div class="input-group mb-3">
                <input type="text" name="keywords" class="form-control" value="{{ keyword }}" maxlength="40" required>
                <button class="btn btn-outline-secondary add-key" type="button"><i
                        class="fa-solid fa-plus"></i></button>
            </div>
            {% endif %}
            {% endfor %}
        </div>
        <button id="save_button" type="submit" class="btn btn-primary">Save</button>
    </form>
</div>
{% endblock %}

{% block script %}
<script>
    function append_button() {
        const div = document.createElement("div");
        div.classList.add("input-group", "mb-3");

        const input = document.createElement("input");
        input.type = "text";
        input.classList.add("form-control");
        input.maxLength = 40;
        input.required = true;
        input.name = "keywords";

        const plus_button = document.createElement("button");
        plus_button.classList.add("btn", "btn-outline-secondary", "add-key");
        plus_button.type = "button";
        plus_button.innerHTML = '<i class="fa-solid fa-plus"></i>';
        plus_button.addEventListener("click", append_button);

        const minus_button = document.createElement("button");
        minus_button.classList.add("btn", "btn-outline-secondary", "sub-key");
        minus_button.type = "button";
        minus_button.innerHTML = '<i class="fa-solid fa-minus"></i>';
        minus_button.addEventListener("click", () => {
            minus_button.parentElement.remove();
        });

        div.appendChild(input);
        div.appendChild(plus_button);
        div.appendChild(minus_button);

        document.getElementById("save_button").before(div);
    }

    let add_keys = document.getElementsByClassName("add-key");
    Array.from(add_keys).forEach((add_key) => {
        add_key.addEventListener("click", append_button);
    });

    let sub_keys = document.getElementsByClassName("sub-key");
    Array.from(sub_keys).forEach((sub_key) => {
        sub_key.addEventListener("click", () => {
            sub_key.parentElement.remove();
        });
    });
</script>
{% endblock %}

templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'chart:index' %}"><img src="{% static 'images/logo.svg' %}"
                                                                    alt="logo"/></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    {% url 'chart:index' as index %}
                    <a class="nav-link {% if request.path == index %}active{% endif %}" href="{{ index }}">Home</a>
                </li>
                <li class="nav-item">
                    {% url 'chart:keywords' as keywords %}
                    <a class="nav-link {% if request.path == keywords %}active{% endif %}" href="{{ keywords }}">Keywords</a>
                </li>
            </ul>
        </div>
        <div class="nav-item">
            <a class="nav-link" href="/admin">Admin</a>
        </div>
    </div>
</nav>